import React from 'react';
import {
  Box,
  Typography,
  Container,
  Link,
  useTheme,
  alpha,
  Stack,
  Divider,
} from '@mui/material';
import { Security as SecurityIcon } from '@mui/icons-material';
import PageHeader from '../components/common/PageHeader';
import {
  getSectionHeaderStyle,
  subHeaderStyle,
  bodyStyle,
  listStyle,
} from '../styles/legalStyles';

const PrivacyPolicy = () => {
  const theme = useTheme();
  const sectionHeaderStyle = getSectionHeaderStyle(theme);

  return (
    <Container maxWidth="md" sx={{ py: 4 }}>
      <Box
        sx={{
          p: { xs: 3, md: 5 },
          borderRadius: 3,
          border: '1px solid',
          borderColor: alpha(theme.palette.divider, 0.1),
          bgcolor: theme.palette.background.paper,
          boxShadow: `0 4px 24px ${alpha(theme.palette.common.black || '#000', 0.02)}`,
        }}
      >
        <PageHeader
          title="Data Privacy Protocol"
          subtitle="Information collection, usage policies, and system security measures."
          icon={SecurityIcon}
        />

        <Typography sx={bodyStyle}>
          This Privacy Policy describes Our policies and procedures on the
          collection, use and disclosure of Your information when You use the
          Service and tells You about Your privacy rights and how the law
          protects You.
        </Typography>

        <Typography variant="h2" sx={sectionHeaderStyle}>
          Interpretation and Definitions
        </Typography>

        <Typography variant="h3" sx={subHeaderStyle}>
          Interpretation
        </Typography>
        <Typography sx={bodyStyle}>
          The words of which the initial letter is capitalized have meanings
          defined under the following conditions. The following definitions
          shall have the same meaning regardless of whether they appear in
          singular or in plural.
        </Typography>

        <Typography variant="h3" sx={subHeaderStyle}>
          Definitions
        </Typography>
        <Typography sx={bodyStyle}>
          For the purposes of this Privacy Policy:
        </Typography>
        <Box component="ul" sx={listStyle}>
          <li>
            <strong>Account</strong> means a unique account created for You to
            access our Service or parts of our Service.
          </li>
          <li>
            <strong>Company</strong> (referred to as either "the Company", "We",
            "Us" or "Our" in this Agreement) refers to Your Website.
          </li>
          <li>
            <strong>Cookies</strong> are small files that are placed on Your
            computer, mobile device or any other device by a website, containing
            the details of Your browsing history on that website among its many
            uses.
          </li>
          <li>
            <strong>Country</strong> refers to: India
          </li>
          <li>
            <strong>Device</strong> means any device that can access the Service
            such as a computer, a cellphone or a digital tablet.
          </li>
          <li>
            <strong>Personal Data</strong> is any information that relates to an
            identified or identifiable individual.
          </li>
          <li>
            <strong>Service</strong> refers to the Website.
          </li>
          <li>
            <strong>Service Provider</strong> means any natural or legal person
            who processes the data on behalf of the Company. It refers to
            third-party companies or individuals employed by the Company to
            facilitate the Service.
          </li>
          <li>
            <strong>Usage Data</strong> refers to data collected automatically,
            either generated by the use of the Service or from the Service
            infrastructure itself.
          </li>
          <li>
            <strong>Website</strong> refers to SmartFund Manager, accessible
            from{' '}
            <Link href="#" sx={{ color: 'primary.main', fontWeight: 600 }}>
              https://yourwebsite.com/
            </Link>
          </li>
          <li>
            <strong>You</strong> means the individual accessing or using the
            Service, or the company, or other legal entity on behalf of which
            such individual is accessing or using the Service.
          </li>
        </Box>

        <Typography variant="h2" sx={sectionHeaderStyle}>
          Collecting and Using Your Personal Data
        </Typography>

        <Typography variant="h3" sx={subHeaderStyle}>
          Types of Data Collected
        </Typography>

        <Typography
          variant="h4"
          sx={{ ...subHeaderStyle, fontSize: '0.95rem' }}
        >
          Personal Data
        </Typography>
        <Typography sx={bodyStyle}>
          While using Our Service, We may ask You to provide Us with certain
          personally identifiable information that can be used to contact or
          identify You. Personally identifiable information may include, but is
          not limited to:
        </Typography>
        <Box component="ul" sx={listStyle}>
          <li>Email address</li>
          <li>First name and last name</li>
          <li>Phone number</li>
          <li>Address, State, Province, ZIP/Postal code, City</li>
          <li>Usage Data</li>
        </Box>

        <Typography
          variant="h4"
          sx={{ ...subHeaderStyle, fontSize: '0.95rem' }}
        >
          Usage Data
        </Typography>
        <Typography sx={bodyStyle}>
          Usage Data is collected automatically when using the Service.
        </Typography>
        <Typography sx={bodyStyle}>
          Usage Data may include information such as Your Device's Internet
          Protocol address (e.g. IP address), browser type, browser version, the
          pages of our Service that You visit, the time and date of Your visit,
          the time spent on those pages, unique device identifiers and other
          diagnostic data.
        </Typography>

        <Typography
          variant="h4"
          sx={{ ...subHeaderStyle, fontSize: '0.95rem' }}
        >
          Tracking Technologies and Cookies
        </Typography>
        <Typography sx={bodyStyle}>
          We use Cookies and similar tracking technologies to track the activity
          on Our Service and store certain information. Tracking technologies
          used are beacons, tags, and scripts to collect and track information
          and to improve and analyze Our Service. The technologies We use may
          include:
        </Typography>
        <Box component="ul" sx={listStyle}>
          <li>
            <strong>Cookies or Browser Cookies.</strong> A cookie is a small
            file placed on Your Device. You can instruct Your browser to refuse
            all Cookies or to indicate when a Cookie is being sent.
          </li>
          <li>
            <strong>Flash Cookies.</strong> Certain features of our Service may
            use local stored objects (or Flash Cookies) to collect and store
            information about Your preferences.
          </li>
          <li>
            <strong>Web Beacons.</strong> Certain sections of our Service and
            our emails may contain small electronic files known as web beacons.
          </li>
        </Box>

        <Typography variant="h2" sx={sectionHeaderStyle}>
          Disclosure of Your Personal Data
        </Typography>

        <Typography variant="h3" sx={subHeaderStyle}>
          Business Transactions
        </Typography>
        <Typography sx={bodyStyle}>
          If the Company is involved in a merger, acquisition or asset sale,
          Your Personal Data may be transferred. We will provide notice before
          Your Personal Data is transferred and becomes subject to a different
          Privacy Policy.
        </Typography>

        <Typography variant="h3" sx={subHeaderStyle}>
          Law enforcement
        </Typography>
        <Typography sx={bodyStyle}>
          Under certain circumstances, the Company may be required to disclose
          Your Personal Data if required to do so by law or in response to valid
          requests by public authorities (e.g. a court or a government agency).
        </Typography>

        <Typography variant="h2" sx={sectionHeaderStyle}>
          Security of Your Personal Data
        </Typography>
        <Typography sx={bodyStyle}>
          The security of Your Personal Data is important to Us, but remember
          that no method of transmission over the Internet, or method of
          electronic storage is 100% secure. While We strive to use commercially
          acceptable means to protect Your Personal Data, We cannot guarantee
          its absolute security.
        </Typography>

        <Divider
          sx={{ my: 4, borderColor: alpha(theme.palette.divider, 0.1) }}
        />

        <Typography variant="h3" sx={subHeaderStyle}>
          Contact Us
        </Typography>
        <Typography sx={bodyStyle}>
          If you have any questions regarding this security protocol, You can
          contact the engineering team:
        </Typography>
        <Box component="ul" sx={{ ...listStyle, mb: 0 }}>
          <li>
            By email: <strong>support@yourwebsite.com</strong>
          </li>
          <li>
            By visiting this page on our website:{' '}
            <Link href="#" sx={{ color: 'primary.main', fontWeight: 600 }}>
              https://yourwebsite.com/contact
            </Link>
          </li>
        </Box>
      </Box>
    </Container>
  );
};

export default PrivacyPolicy;
